- name: Install PHP and modules
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present
    update_cache: yes

- name: Restart Apache to load PHP
  service:
    name: apache2
    state: restarted
